// 决策室类型定义 - 基于 PRD Appendix v1.0

// 议题状态
export type IssueStatus =
  | 'DRAFT'
  | 'INITIALIZING'
  | 'OPEN'
  | 'DISCUSSING'
  | 'PENDING_HUMAN'
  | 'RESOLVED'
  | 'CANCELLED'
  | 'SUSPENDED'
  | 'FROZEN'
  | 'EXPIRED';

// 议题大类
export type IssueCategory =
  | 'customer_urgent_order'
  | 'production_line_switch'
  | 'bom_change'
  | 'quality_anomaly'
  | 'material_shortage'
  | 'equipment_breakdown'
  | 'capacity_allocation'
  | 'supplier_change'
  | 'pricing_decision'
  | 'supplier_qualification'
  | 'budget_adjustment'
  | 'other';

// 敏感级
export type SensitivityLevel = 'normal' | 'sensitive' | 'highly_sensitive';

// 紧急度
export type UrgencyLevel = 'normal' | 'urgent' | 'critical';

// 角色 ID
export type RoleId =
  | 'ceo'
  | 'vp_prod'
  | 'vp_sales'
  | 'mgr_plan'
  | 'mgr_process'
  | 'mgr_quality'
  | 'mgr_finance'
  | 'mgr_sales'
  | 'mgr_purchase'
  | 'mgr_factory'
  | 'coord_agent';

// 用户
export interface User {
  id: string;
  role_id: RoleId;
  name: string;
  title: string;
  department: string;
  email: string;
  factory_scope: string[];
  product_line_scope: string[];
  is_active: boolean;
}

// Agent
export interface Agent {
  id: string;
  user_id: string | null;
  display_name: string;
  avatar_initial: string;
  stance_config: {
    risk_preference: 'conservative' | 'balanced' | 'aggressive';
    key_constraints: string[];
    delegation_scope: string[];
  };
  knowledge_sources: string[];
  is_active: boolean;
  last_synced_at: string;
}

// 角色定义
export interface Role {
  id: RoleId;
  name: string;
  department: string;
  isAgent: boolean;
  isSystem?: boolean;
}

// 议题画像(资产01)
export interface IssueProfile {
  category: IssueCategory;
  tags: string[];
  entities: Array<{
    type: string;
    id: string;
    name: string;
  }>;
  summary: string;
  autoGenerated: boolean;
}

// 关键权衡(资产02)
export interface Tradeoff {
  sideA: string;
  sideB: string;
  weightA: number;
  weightB: number;
  reasoning: string;
}

export interface KeyTradeoffs {
  tradeoffs: Tradeoff[];
}

// 决策依据(资产03)
export interface DataPoint {
  name: string;
  value: string;
  source: string;
  sourceRef?: string;
  confidence: 'high' | 'medium' | 'low';
}

export interface DecisionBasis {
  dataPoints: DataPoint[];
}

// 决策结论(资产04)
export interface DecisionResolution {
  resolutionText: string;
  resolutionType: 'ai_consensus_then_human_confirmed' | 'human_overridden' | 'pending';
  resolverUserId?: string;
  resolverName?: string;
  resolvedAt?: string;
  dissentingViews?: Array<{
    role: RoleId;
    view: string;
  }>;
  escalationPath?: string[];
}

// 可复用规则(资产05)
export interface ReusableRule {
  ruleText: string;
  triggerPattern: {
    category?: IssueCategory;
    conditions: Array<{
      field: string;
      operator: string;
      value?: any;
    }>;
  };
  recommendedAction: string;
  applicableScope: {
    plants?: string[];
    productionLines?: string[];
    customerTiers?: string[];
  };
  confidenceScore: number;
  humanApproved: boolean;
}

// 资产类型联合
export type AssetType = '01' | '02' | '03' | '04' | '05';
export type AssetTypeName = 'ISSUE_PROFILE' | 'KEY_TRADEOFFS' | 'DECISION_BASIS' | 'CONCLUSION' | 'REUSABLE_RULE';

export type DecisionAsset =
  | { type: '01'; typeName: 'ISSUE_PROFILE'; content: IssueProfile }
  | { type: '02'; typeName: 'KEY_TRADEOFFS'; content: KeyTradeoffs }
  | { type: '03'; typeName: 'DECISION_BASIS'; content: DecisionBasis }
  | { type: '04'; typeName: 'CONCLUSION'; content: DecisionResolution }
  | { type: '05'; typeName: 'REUSABLE_RULE'; content: ReusableRule };

// Mention 类型
export interface Mention {
  start: number;
  end: number;
  type: 'ROLE' | 'ESCALATE' | 'HISTORY';
  target_role_id?: RoleId;
  target_display?: string;
}

// 消息
export interface Message {
  id: string;
  topic_id: string;
  author_type: 'agent' | 'human';
  author_id: string;
  author_display: string;
  author_color_class: 'primary' | 'accent' | 'neutral';
  message_type: 'STATEMENT' | 'CONSENSUS' | 'QUESTION' | 'ESCALATION';
  content: string;
  mentions?: Mention[];
  reply_to_message_id?: string | null;
  reasoning_path?: {
    ontology_refs: string[];
  };
  attached_data?: Record<string, any> | null;
  is_pinned: boolean;
  created_at: string;
  created_at_display: string;
}

// 议题
export interface Issue {
  id: string;
  title: string;
  description: string;
  category?: IssueCategory;
  status: IssueStatus;
  urgency: UrgencyLevel;
  sensitivity: SensitivityLevel;
  plants?: string[];
  productionLines?: string[];
  creator_user_id: string;
  creatorName?: string;
  participant_role_ids?: RoleId[];
  whitelist_user_ids?: string[];
  ontology_node_ids?: string[];
  parent_topic_id?: string | null;
  referenced_asset_ids?: string[];
  source_template_id?: string | null;
  pending_user_id?: string;
  pendingUserName?: string;
  created_at: string;
  updated_at: string;
  decided_at?: string | null;
  decided_by_user_id?: string | null;
  final_resolution?: string | null;
  referencedIssues?: Array<{
    id: string;
    title: string;
    resolution?: string;
  }>;
}

// 决策状态
export interface ResolutionStatus {
  consensusSummary?: string;
  pendingQuestion?: string;
  pending_user_id?: string;
  pendingUserName?: string;
  options: Array<{
    id: string;
    label: string;
    isRecommended: boolean;
    isFollowup?: boolean;
  }>;
}

// 控制规则
export interface ActiveControl {
  type: string;
  ruleText: string;
  currentlyActive: boolean;
}

// 视野计数
export interface ScopeCounts {
  pending: number;
  watching: number;
  decided: number;
  global?: number | null;
  restricted: number;
}

// Agent 加载状态
export interface AgentLoadingStatus {
  role: RoleId;
  status: 'loading' | 'ready' | 'failed';
}

// 通知
export interface Notification {
  id: string;
  user_id: string;
  notification_type: 'ESCALATED' | 'TOPIC_DECIDED' | 'MENTIONED' | 'CONSENSUS_REACHED';
  title: string;
  preview: string;
  topic_id?: string;
  is_read: boolean;
  created_at: string;
}

// 决策日志
export interface DecisionLog {
  id: string;
  topic_id: string;
  decision_type: 'APPROVE' | 'OVERRIDE' | 'REJECT';
  decided_by_user_id: string;
  decision_text: string;
  ai_consensus_at_time?: string;
  override_reason?: string | null;
  created_at: string;
}

// 资产引用
export interface AssetReference {
  id: string;
  source_asset_id: string;
  target_topic_id: string;
  reference_type: 'INIT_DRAFT' | 'INLINE_CITE' | 'RULE_TRIGGERED';
  created_at: string;
}
